<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Syed" ignored="0" name="Default test" tests="8" failures="1" timestamp="27 Sep 2019 04:58:22 GMT" time="0.109" errors="0">
  <testcase name="m" time="0.015" classname="learnTestNG.TestNGDemo1"/>
  <testcase name="m1" time="0.002" classname="learnTestNG.TestNGDemo1"/>
  <testcase name="m2" time="0.001" classname="learnTestNG.TestNGDemo1"/>
  <testcase name="m3" time="0.003" classname="learnTestNG.TestNGDemo1">
    <failure type="java.lang.AssertionError" message="Method m3() was purposelyfailed to understand depends behavior in TestNG">
      <![CDATA[java.lang.AssertionError: Method m3() was purposelyfailed to understand depends behavior in TestNG
at org.testng.Assert.fail(Assert.java:96)
at learnTestNG.TestNGDemo1.m3(TestNGDemo1.java:32)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- m3 -->
  <testcase name="m4" time="0.002" classname="learnTestNG.TestNGDemo1"/>
  <testcase name="m4" time="0.002" classname="learnTestNG.TestNGDemo1"/>
  <testcase name="m4" time="0.001" classname="learnTestNG.TestNGDemo1"/>
  <testcase name="m5" time="0.0" classname="learnTestNG.TestNGDemo1">
    <skipped/>
  </testcase> <!-- m5 -->
</testsuite> <!-- Default test -->
